### ISSUE TITLE
"Help wanted" Would you pls share a sample, thanks.

### ISSUE THREAD

**Issue by TerryHoCQ** [NicolasAlmerge/NewHaru#1]
"Help wanted" Would you pls share a sample, thanks.

**Comment by NicolasAlmerge** [comment]
Hello @TerryHoCQ, I just shared a small sample on the [`README.md`](https://github.com/NicolasAlmerge/NewHaru/blob/main/README.md) file. There is also the documentation available [here](https://nicolasalmerge.github.io/NewHaru/annotated.html).

I will probably add more things, but I hope this helps you a bit. Let me know if you have any questions!

**Comment by TerryHoCQ** [comment]
Thank you very much!

**Comment by NicolasAlmerge** [comment]
@TerryHoCQ You're welcome! Does everything work well for you? Don't hesitate to tell me if it doesn't work well or if you want to contribute anything! :)
